#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/CutOptim

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/CutOptim

INC_DEBUG_PROFILE = $(INC) -Iinclude
CFLAGS_DEBUG_PROFILE = $(CFLAGS) -pg -g
RESINC_DEBUG_PROFILE = $(RESINC)
RCFLAGS_DEBUG_PROFILE = $(RCFLAGS)
LIBDIR_DEBUG_PROFILE = $(LIBDIR)
LIB_DEBUG_PROFILE = $(LIB)
LDFLAGS_DEBUG_PROFILE = $(LDFLAGS) -pg
OBJDIR_DEBUG_PROFILE = obj/Debug_Profile
DEP_DEBUG_PROFILE = 
OUT_DEBUG_PROFILE = bin/Debug_Profile/CutOptim

INC_RELEASE_PROFILE = $(INC) -Iinclude
CFLAGS_RELEASE_PROFILE = $(CFLAGS) -O2 -pg -g
RESINC_RELEASE_PROFILE = $(RESINC)
RCFLAGS_RELEASE_PROFILE = $(RCFLAGS)
LIBDIR_RELEASE_PROFILE = $(LIBDIR)
LIB_RELEASE_PROFILE = $(LIB)
LDFLAGS_RELEASE_PROFILE = $(LDFLAGS) -pg
OBJDIR_RELEASE_PROFILE = obj/Release_Profile
DEP_RELEASE_PROFILE = 
OUT_RELEASE_PROFILE = bin/Release_Profile/CutOptim

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/src/CachePosition.o $(OBJDIR_DEBUG)/src/ConvexHull.o $(OBJDIR_DEBUG)/src/Geometry.o $(OBJDIR_DEBUG)/src/SvgDoc.o $(OBJDIR_DEBUG)/src/SvgPath.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/CachePosition.o $(OBJDIR_RELEASE)/src/ConvexHull.o $(OBJDIR_RELEASE)/src/Geometry.o $(OBJDIR_RELEASE)/src/SvgDoc.o $(OBJDIR_RELEASE)/src/SvgPath.o

OBJ_DEBUG_PROFILE = $(OBJDIR_DEBUG_PROFILE)/main.o $(OBJDIR_DEBUG_PROFILE)/src/CachePosition.o $(OBJDIR_DEBUG_PROFILE)/src/ConvexHull.o $(OBJDIR_DEBUG_PROFILE)/src/Geometry.o $(OBJDIR_DEBUG_PROFILE)/src/SvgDoc.o $(OBJDIR_DEBUG_PROFILE)/src/SvgPath.o

OBJ_RELEASE_PROFILE = $(OBJDIR_RELEASE_PROFILE)/main.o $(OBJDIR_RELEASE_PROFILE)/src/CachePosition.o $(OBJDIR_RELEASE_PROFILE)/src/ConvexHull.o $(OBJDIR_RELEASE_PROFILE)/src/Geometry.o $(OBJDIR_RELEASE_PROFILE)/src/SvgDoc.o $(OBJDIR_RELEASE_PROFILE)/src/SvgPath.o

all: debug release debug_profile release_profile

clean: clean_debug clean_release clean_debug_profile clean_release_profile

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/src/CachePosition.o: src/CachePosition.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/CachePosition.cpp -o $(OBJDIR_DEBUG)/src/CachePosition.o

$(OBJDIR_DEBUG)/src/ConvexHull.o: src/ConvexHull.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ConvexHull.cpp -o $(OBJDIR_DEBUG)/src/ConvexHull.o

$(OBJDIR_DEBUG)/src/Geometry.o: src/Geometry.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Geometry.cpp -o $(OBJDIR_DEBUG)/src/Geometry.o

$(OBJDIR_DEBUG)/src/SvgDoc.o: src/SvgDoc.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SvgDoc.cpp -o $(OBJDIR_DEBUG)/src/SvgDoc.o

$(OBJDIR_DEBUG)/src/SvgPath.o: src/SvgPath.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SvgPath.cpp -o $(OBJDIR_DEBUG)/src/SvgPath.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/CachePosition.o: src/CachePosition.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/CachePosition.cpp -o $(OBJDIR_RELEASE)/src/CachePosition.o

$(OBJDIR_RELEASE)/src/ConvexHull.o: src/ConvexHull.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ConvexHull.cpp -o $(OBJDIR_RELEASE)/src/ConvexHull.o

$(OBJDIR_RELEASE)/src/Geometry.o: src/Geometry.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Geometry.cpp -o $(OBJDIR_RELEASE)/src/Geometry.o

$(OBJDIR_RELEASE)/src/SvgDoc.o: src/SvgDoc.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SvgDoc.cpp -o $(OBJDIR_RELEASE)/src/SvgDoc.o

$(OBJDIR_RELEASE)/src/SvgPath.o: src/SvgPath.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SvgPath.cpp -o $(OBJDIR_RELEASE)/src/SvgPath.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

before_debug_profile: 
	test -d bin/Debug_Profile || mkdir -p bin/Debug_Profile
	test -d $(OBJDIR_DEBUG_PROFILE) || mkdir -p $(OBJDIR_DEBUG_PROFILE)
	test -d $(OBJDIR_DEBUG_PROFILE)/src || mkdir -p $(OBJDIR_DEBUG_PROFILE)/src

after_debug_profile: 

debug_profile: before_debug_profile out_debug_profile after_debug_profile

out_debug_profile: before_debug_profile $(OBJ_DEBUG_PROFILE) $(DEP_DEBUG_PROFILE)
	$(LD) $(LIBDIR_DEBUG_PROFILE) -o $(OUT_DEBUG_PROFILE) $(OBJ_DEBUG_PROFILE)  $(LDFLAGS_DEBUG_PROFILE) $(LIB_DEBUG_PROFILE)

$(OBJDIR_DEBUG_PROFILE)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG_PROFILE) $(INC_DEBUG_PROFILE) -c main.cpp -o $(OBJDIR_DEBUG_PROFILE)/main.o

$(OBJDIR_DEBUG_PROFILE)/src/CachePosition.o: src/CachePosition.cpp
	$(CXX) $(CFLAGS_DEBUG_PROFILE) $(INC_DEBUG_PROFILE) -c src/CachePosition.cpp -o $(OBJDIR_DEBUG_PROFILE)/src/CachePosition.o

$(OBJDIR_DEBUG_PROFILE)/src/ConvexHull.o: src/ConvexHull.cpp
	$(CXX) $(CFLAGS_DEBUG_PROFILE) $(INC_DEBUG_PROFILE) -c src/ConvexHull.cpp -o $(OBJDIR_DEBUG_PROFILE)/src/ConvexHull.o

$(OBJDIR_DEBUG_PROFILE)/src/Geometry.o: src/Geometry.cpp
	$(CXX) $(CFLAGS_DEBUG_PROFILE) $(INC_DEBUG_PROFILE) -c src/Geometry.cpp -o $(OBJDIR_DEBUG_PROFILE)/src/Geometry.o

$(OBJDIR_DEBUG_PROFILE)/src/SvgDoc.o: src/SvgDoc.cpp
	$(CXX) $(CFLAGS_DEBUG_PROFILE) $(INC_DEBUG_PROFILE) -c src/SvgDoc.cpp -o $(OBJDIR_DEBUG_PROFILE)/src/SvgDoc.o

$(OBJDIR_DEBUG_PROFILE)/src/SvgPath.o: src/SvgPath.cpp
	$(CXX) $(CFLAGS_DEBUG_PROFILE) $(INC_DEBUG_PROFILE) -c src/SvgPath.cpp -o $(OBJDIR_DEBUG_PROFILE)/src/SvgPath.o

clean_debug_profile: 
	rm -f $(OBJ_DEBUG_PROFILE) $(OUT_DEBUG_PROFILE)
	rm -rf bin/Debug_Profile
	rm -rf $(OBJDIR_DEBUG_PROFILE)
	rm -rf $(OBJDIR_DEBUG_PROFILE)/src

before_release_profile: 
	test -d bin/Release_Profile || mkdir -p bin/Release_Profile
	test -d $(OBJDIR_RELEASE_PROFILE) || mkdir -p $(OBJDIR_RELEASE_PROFILE)
	test -d $(OBJDIR_RELEASE_PROFILE)/src || mkdir -p $(OBJDIR_RELEASE_PROFILE)/src

after_release_profile: 

release_profile: before_release_profile out_release_profile after_release_profile

out_release_profile: before_release_profile $(OBJ_RELEASE_PROFILE) $(DEP_RELEASE_PROFILE)
	$(LD) $(LIBDIR_RELEASE_PROFILE) -o $(OUT_RELEASE_PROFILE) $(OBJ_RELEASE_PROFILE)  $(LDFLAGS_RELEASE_PROFILE) $(LIB_RELEASE_PROFILE)

$(OBJDIR_RELEASE_PROFILE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE_PROFILE) $(INC_RELEASE_PROFILE) -c main.cpp -o $(OBJDIR_RELEASE_PROFILE)/main.o

$(OBJDIR_RELEASE_PROFILE)/src/CachePosition.o: src/CachePosition.cpp
	$(CXX) $(CFLAGS_RELEASE_PROFILE) $(INC_RELEASE_PROFILE) -c src/CachePosition.cpp -o $(OBJDIR_RELEASE_PROFILE)/src/CachePosition.o

$(OBJDIR_RELEASE_PROFILE)/src/ConvexHull.o: src/ConvexHull.cpp
	$(CXX) $(CFLAGS_RELEASE_PROFILE) $(INC_RELEASE_PROFILE) -c src/ConvexHull.cpp -o $(OBJDIR_RELEASE_PROFILE)/src/ConvexHull.o

$(OBJDIR_RELEASE_PROFILE)/src/Geometry.o: src/Geometry.cpp
	$(CXX) $(CFLAGS_RELEASE_PROFILE) $(INC_RELEASE_PROFILE) -c src/Geometry.cpp -o $(OBJDIR_RELEASE_PROFILE)/src/Geometry.o

$(OBJDIR_RELEASE_PROFILE)/src/SvgDoc.o: src/SvgDoc.cpp
	$(CXX) $(CFLAGS_RELEASE_PROFILE) $(INC_RELEASE_PROFILE) -c src/SvgDoc.cpp -o $(OBJDIR_RELEASE_PROFILE)/src/SvgDoc.o

$(OBJDIR_RELEASE_PROFILE)/src/SvgPath.o: src/SvgPath.cpp
	$(CXX) $(CFLAGS_RELEASE_PROFILE) $(INC_RELEASE_PROFILE) -c src/SvgPath.cpp -o $(OBJDIR_RELEASE_PROFILE)/src/SvgPath.o

clean_release_profile: 
	rm -f $(OBJ_RELEASE_PROFILE) $(OUT_RELEASE_PROFILE)
	rm -rf bin/Release_Profile
	rm -rf $(OBJDIR_RELEASE_PROFILE)
	rm -rf $(OBJDIR_RELEASE_PROFILE)/src

install:
	cp -f $(OUT_RELEASE) ~/.local/bin

install_inkscape:
	cp -f cutoptim.inx $(OUT_RELEASE) ~/.config/inkscape/extensions

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release before_debug_profile after_debug_profile clean_debug_profile before_release_profile after_release_profile clean_release_profile

